### DISCUSSION TITLE
How to properly set up a firewall?

### DISCUSSION THREAD

**Discussion by kolserdav** [coturn/coturn#1078] [Q&A]
I work at `Centos 7` from `firewall-cmd`.
Configuration `coturn` is like this:
```
fingerprint
lt-cred-mech
simple-log
listening-ip=PUBLIC_IP
listening-ip=PUBLIC_IP2
listening-ip=127.0.0.1
listening-ip=127.0.0.2
user=name:pass
realm=DOMAIN
listening-port=3478
min-port=49000
max-port=59000
log-file=/var/log/coturn/turnserver.log
verbose
```
The firewall is configured like this:
```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: dhcpv6-client http https ssh
  ports: 5349/tcp 3479/udp 3479/tcp 3478/tcp  3478/udp  49000-59000/tcp  49000-59000/udp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
If the firewall is off, then everything works fine. But if it is enabled, then most of the connections do not pass through the firewall.
When the firewall is enabled, I get the following errors:
```
url: turn:PUBLIC_IP2:3478?transport=udp
address: 192.168.0.x
port: 56801
host_candidate: 192.168.0.x:56801
error_text: TURN allocate request timed out.
error_code: 701
```

It seems that I have already opened all possible ports, but for some reason it only works with the firewall turned off.
Any ideas?
