### DISCUSSION TITLE
How to properly setup user:password auth?

### DISCUSSION THREAD

**Discussion by woj-tek** [coturn/coturn#1477] [Q&A]
I'm using docker-compose, relative simple configuration:

```yaml
  coturn:
    image: coturn/coturn
    restart: unless-stopped
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      # - 49152-65535:49152-65535/udp
      - 61385-61388:61385-61385/udp
    # network_mode: host
    environment:
      - DETECT_EXTERNAL_IP=yes
      - DETECT_RELAY_IP=yes
    command:
      - -n
      - --log-file=stdout
      - -v
      - --min-port=49160
      - --max-port=49200
      - --realm=localhost
      - --user=username:password
      - --lt-cred-mech
      - --fingerprint
    volumes:
      - ./config/coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./.cache/coturn/data:/var/lib/coturn
```

And while testing with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ or https://icetest.info/ I don't get the proper results and in coturn logs I get:

```
coturn-1  | 2698: (22): INFO: session 005000000000000001: realm <localhost> user <>: incoming packet message processed, error 401: Unauthorized
coturn-1  | 2698: (21): INFO: session 004000000000000001: realm <localhost> user <>: incoming packet message processed, error 401: Unauthorized
coturn-1  | 2699: (22): INFO: session 005000000000000001: realm <localhost> user <>: incoming packet message processed, error 401: Unauthorized
coturn-1  | 2699: (21): INFO: session 004000000000000001: realm <localhost> user <>: incoming packet message processed, error 401: Unauthorized
coturn-1  | 2701: (22): INFO: session 005000000000000001: realm <localhost> user <>: incoming packet message processed, error 401: Unauthorized
coturn-1  | 2701: (21): INFO: session 004000000000000001: realm <localhost> user <>: incoming packet message processed, error 401: Unauthorized
```

And even more verbose:
```
coturn-1  | 27: (20): INFO: udp_server_input_handler:601:start
coturn-1  | 27: (20): INFO: open_client_connection_session:4581:start
coturn-1  | 27: (20): INFO: read_client_connection:4368:start
coturn-1  | 27: (20): INFO: read_client_connection: data.buffer=0xffff7400547c, data.len=44
coturn-1  | 27: (20): INFO: session 003000000000000001: realm <localhost> user <>: incoming packet message processed, error 401: Unauthorized
coturn-1  | 27: (20): INFO: write_client_connection:4164:start
coturn-1  | 27: (20): INFO: write_client_connection: prepare to write to s 0xffff74015480
coturn-1  | 27: (20): INFO: write_client_connection:4185:end
coturn-1  | 27: (20): INFO: read_client_connection:4473:end
coturn-1  | 27: (20): INFO: open_client_connection_session:4612:end
coturn-1  | 27: (20): INFO: udp_server_input_handler:647:end
coturn-1  | 27: (25): INFO: udp_server_input_handler:601:start
coturn-1  | 27: (25): INFO: open_client_connection_session:4581:start
coturn-1  | 27: (25): INFO: read_client_connection:4368:start
coturn-1  | 27: (25): INFO: read_client_connection: data.buffer=0xffff5c004fdc, data.len=44
```

I do have user and password setup on the pages but still get `user <>:` -- any idea what I'm doing wrong?
