### DISCUSSION TITLE
Docker Container will not start

### DISCUSSION THREAD

**Discussion by egelhaus** [coturn/coturn#1680] [Support]
Hey,
I wanted to install coTURN on an fresh install with docker compose and no matter what I try the container will not start, it got stuck on "starting" for like 15m before I manually had to reboot my machine becuase it couldnt stop it.

This is my docker-compose.yml:
```
version: '3.8'
services:
  coturn:
    image: coturn/coturn
    restart: unless-stopped
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49152-65535:49152-65535/udp"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./ssl:/etc/coturn/certs:ro
    environment:
      - DETECT_EXTERNAL_IP=yes
```

This is my turnserver.conf
```
listening-port=3478
tls-listening-port=5349
min-port=49152
max-port=65535
realm=REDACTED.de
server-name=REDACTED.de
fingerprint
lt-cred-mech
user=REDACTED
total-quota=100
bps-capacity=0
stale-nonce=600
cert=/etc/coturn/certs/cert.crt
pkey=/etc/coturn/certs/pkey.pem`
```

The Certificates are in the correct folder and named correctly, and have been given the right Permissions.
OS: Ubuntu 24.04
Docker Version: 28.0.4
Docker Compose Version: v2.34.0

Thanks in Regards
