### ISSUE TITLE
External calls can't connect

### ISSUE THREAD

**Issue by Eirikr70** [coturn/coturn#1129]
Hello,
So I have installed a TURN server with Docker together with a Synapse server and a Mysql database. I have open the ports through NAT rules. The certificates are found and installed. I can establish a communication within my LAN (which is quite useless) but the calls never connect whenever a contact is outside my network ("Call connecting"). I hope someone can help me out.
Here is my docker-compose
```
version: "3"
services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_NO_TLS=1
      - SYNAPSE_SERVER_NAME=matrix.memyself.fr
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      - TZ="Europe/Paris"
    volumes:
      - ./synapse-data:/datagi
      - ./data:/data
    ports:
      - 8008:8008
    networks:
      matrix:
        ipv4_address: 10.10.10.2
  coturn:
    container_name: coturn
    image: coturn/coturn:latest
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      - 49152-49272:49152-49272/udp
    environment:
      - TZ="Europe/Paris"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
      - /etc/letsencrypt/archive/memyself.fr:/letsencrypt
    env_file:
      - mysql/mysql.env
    networks:
      matrix:
        ipv4_address: 10.10.10.5
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
  mysql:
    image: mariadb
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./mysql/init-coturn-db.sql:/docker-entrypoint-initdb.d/init-coturn-db.sql:ro
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./mysql-data:/var/lib/mysql/data
    env_file: 
      - mysql/mysql.env
    environment:
      - TZ="Europe/Paris"
    networks:
      matrix:
        ipv4_address: 10.10.10.6

networks:
  matrix:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
```
And my turnserver.conf
```
listening-port=3478
tls-listening-port=5349
listening-ip=10.10.10.5
listening-ip=127.0.0.1
relay-ip=10.10.10.5
external-ip=xx.xxx.x.xxx/10.10.10.5
min-port=49152
max-port=49272
verbose
use-auth-secret
static-auth-secret="arealhardsecret"
mysql-userdb="host=mysql dbname=coturn user=coturn password=anothersecret port=3306 connect_timeout=10 read_timeout=10"
realm=memyself.fr
user-quota=12
total-quota=48
no-tcp-relay
cert=/letsencrypt/fullchain1.pem
pkey=/letsencrypt/privkey1.pem
syslog
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.88.99.0-192.88.99.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=240.0.0.0-255.255.255.255
allowed-peer-ip=10.10.10.5
cli-ip=127.0.0.1
cli-port=5766
cli-password="soverysecret"
```
