### ISSUE TITLE
Command args aren't passed on kubernetes

### ISSUE THREAD

**Issue by k-kai** [coturn/coturn#1154]
Hi everyone.
I'm using coturn on Kubernetes, and it was working.
But at version 4.6.1 Kubernetes container args aren't passed to Entrypoint correctly. 

```
contaners:
 - image: coturn/coturn:4.6.1
   args:
     - -c /app/config/turn/turn.conf
     - --external-ip=$(detect-external-ip)
```

I think that it's caused by #1110.

So I want to know how to pass args to entrypoint at version 4.6.1.

Thanks.

**Comment by tyranron** [comment]
@k-kai сould you provide more details and logs what is actually passed to container?

**Comment by k-kai** [comment]
@tyranron 
Of course.

I specified my custom config file and external-ip by command args.
So I expect to execute this command when I apply the Coturn server on a Kubernetes cluster.
```
turnserver -c /app/config/turn/turn.conf --external-ip=$(detect-external-ip)
```

But, logs show that the server seems to try to find out a default config file.
```
0: : log file opened: /var/tmp/turn_1_2023-02-03.log
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.6.1 'Gorst'
0: : 
Max number of open files/sockets allowed for this process: 1048576
0: : 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: : 
```

I think that args aren't passed to container by v4.6.1, though It was working by v4.6.0.

**Comment by tyranron** [comment]
@k-kai have you tried to specify either
```yaml
contaners:
 - image: coturn/coturn:4.6.1
   args:
     - -c 
     - /app/config/turn/turn.conf
     - --external-ip=$(detect-external-ip)
```
or
```yaml
contaners:
 - image: coturn/coturn:4.6.1
   args: ["-c", "/app/config/turn/turn.conf", "--external-ip=$(detect-external-ip)"]
```
?
