### ISSUE TITLE
Feature Request: Docker Container Environment variables for secrets

### ISSUE THREAD

**Issue by jessebot** [coturn/coturn#1245]
Thanks for maintaining this project!

Currently, I don't _think_ there's a way to pass in environment variables for `user` and `pgsql-db` in turnserver.conf. This would be really useful for kubernetes deployments, so that we can have the main config file as a configMap and then just fetch environment variables from exiting k8s secrets when it comes to sensitive info. The alternative is to either put the entire configuration file into a k8s secret, or have an init container to inject these variables, which I'm currently doing in my helm chart [here](https://github.com/jessebot/coturn-chart/blob/3d54558c8a081096ee013e06f5ee0bcefeb97097/charts/coturn/templates/deployment.yaml#L119) but that's kind of messy.

**Comment by tyranron** [comment]
@jessebot in our Helm charts we do something like this:
```yaml
          args:
            - --log-file=stdout
            - --external-ip=$(EXTERNAL_IP)
            - --listening-ip=$(EXTERNAL_IP)
            - --relay-ip=$(EXTERNAL_IP)
            - --redis-userdb=ip=127.0.0.1 port={{ $coturnDb.conf.port | int }} dbname={{ $conf.turn.db.redis.db_number }} password=$(TURN__DB__REDIS__PASS)
            - --redis-statsdb=ip=127.0.0.1 port={{ $coturnDb.conf.port | int }} dbname={{ $conf.turn.db.redis.db_number }} password=$(TURN__DB__REDIS__PASS)
            - --user={{ $conf.turn.user }}:$(TURN__PASS)
            - --cli-password=$(TURN__CLI__PASS)
          {{- with $coturn.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: EXTERNAL_IP
            {{- if index $coturn "conf" "external-ip" }}
              value: {{ index $coturn "conf" "external-ip" | quote }}
            {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- end }}
            - name: TURN__PASS
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s.cred" (include "mychart.fullname" .) | quote }}
                  key: TURN__PASS
            - name: TURN__DB__REDIS__PASS
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s.cred" (include "mychart.fullname" .) | quote }}
                  key: TURN__DB__REDIS__PASS
            - name: TURN__CLI__PASS
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s.cred" (include "mychart.fullname" .) | quote }}
                  key: TURN__CLI__PASS
```
Keep secrets as env vars, but pass them as CLI args. Kubernetes is clever enough to not show them in manifests.

But I agree, that supporting env vars out-of-the-box would be much better.
