### ISSUE TITLE
Prepared docker-compose.yml for dockerized coturn but get Cannot find config file warning

### ISSUE THREAD

**Issue by batusekerci** [coturn/coturn#1277]
My docker-compose.yml is below:

```
turnserver:
        image: coturn/coturn:4.6.2
        restart: always
        network_mode: host
        volumes:
            - ./coturn_files/turnserver.conf:/etc/coturn/turnserver.conf 
```

When I try to run `docker compose up` , I encounter with the warning: **Cannot find config file: turnserver.conf. Default and command-line settings will be used.** 
Do I have to write or use something different? I found an example here [https://gabrieltanner.org/blog/turn-server/](https://gabrieltanner.org/blog/turn-server/) and used it.

**Comment by eakraly** [comment]
Hi @batusekerci !

There is a bug in the docker-compose.yaml file (not your fault - the original post has the issue)
It should be like this:
```
turnserver:
        image: coturn/coturn:4.6.2
        restart: always
        network_mode: host
        volumes:
            - ./coturn_files:/etc/coturn
 ```
The difference is in `volumes` attribute: volume means folder, not a file. You should mount the *folder* that contains turnserver.conf and map it to `/etc/coturn` (which is default folder where config file is looked in).
