### ISSUE TITLE
LeakSanitizer: detected memory leaks in turnutils_rfc5769check

### ISSUE THREAD

**Issue by jonesmz** [coturn/coturn#1368]
```
make check
  shell: /usr/bin/bash -e {0}
  env:
    CFLAGS:  -fsanitize=address 
    LDFLAGS:  -fsanitize=address 
    CC: clang
bin/turnutils_rfc5769check

=================================================================
==3433==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 45 byte(s) in 1 object(s) allocated from:
    #0 0x559564eaa56e in malloc (/home/runner/work/coturn/coturn/bin/turnutils_rfc5769check+0xab56e) (BuildId: 68a2dfa9ec2e0295ec3342eb3d3da5c02db882c3)
    #1 0x559564eed0cf in base64_encode /home/runner/work/coturn/coturn/src/apps/common/apputils.c:1288:32
    #2 0x559564ee71dc in check_oauth /home/runner/work/coturn/coturn/src/apps/rfc5769/rfc5769check.c:78:7
    #3 0x559564ee6bfb in main /home/runner/work/coturn/coturn/src/apps/rfc5769/rfc5769check.c:560:9
    #4 0x7f1004029d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 203de0ae33b53fee1578b117cb4123e85d0534f0)

SUMMARY: AddressSanitizer: 45 byte(s) leaked in 1 allocation(s).
make: *** [Makefile:100: check] Error 1
```
