### ISSUE TITLE
Coturn on only HTTPS/443

### ISSUE THREAD

**Issue by Craftoncu** [coturn/coturn#1626]
Hey,

I'm trying to configure a **Coturn** server to operate solely on **port 443** over **HTTPS** to relay WebRTC traffic in an environment where other ports (e.g., UDP/3478) are blocked. The goal is to ensure Coturn works for applications like WorkAdventure that rely on TURN for media relay, but only over HTTPS/TCP traffic.

Here’s what I’ve done so far:
- Configured Coturn to listen on port 443 with `tls-listening-port=443`.
- Disabled UDP traffic using `no-udp`.
- Routed the traffic through **Traefik**, exposing port 443 with a TCP router.

Despite this setup, when accessing the server, I get a **502 Bad Gateway** error in the browser. I realize Coturn is not an HTTP server, but I would like to confirm the correct way to configure it for HTTPS/TCP-only operation. 

### Specific Questions:
1. Can Coturn function effectively with **TLS termination** handled by Traefik or another reverse proxy, or should Coturn manage TLS itself?
2. Is there a recommended configuration for **Traefik** or similar ingress controllers to properly route TCP/443 traffic to Coturn?
3. Should I enable or adjust specific Coturn options like `use-auth-secret` or `static-auth-secret` for this scenario?
4. Are there additional considerations when using Coturn exclusively over HTTPS for WebRTC?

Here’s my current Coturn configuration:
```ini
realm=turn.wa.kobeg.cloud
use-auth-secret
static-auth-secret=lredacted
fingerprint
external-ip=turn.wa.kobeg.cloud
listening-port=3478
tls-listening-port=443
no-udp
relay-ip=turn.wa.kobeg.cloud
total-quota=100
bps-capacity=0
stale-nonce
verbose
```

And my Traefik TCP IngressRoute configuration:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: coturn-tcp-route
  namespace: workadventure
spec:
  entryPoints:
    - https
  routes:
    - match: HostSNI(`turn.wa.kobeg.cloud`)
      services:
        - name: coturn-wa
          port: 443
  tls:
    passthrough: true
```

Thanks!

---
