### ISSUE TITLE
Can not find private key file but shows found it later

### ISSUE THREAD

**Issue by ulfaric** [coturn/coturn#1648]
coturn  | 0: (1): WARNING: cannot find private key file: /etc/ssl/certs/veilKey.pem (1)
coturn  | 0: (1): WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
coturn  | 0: (1): INFO: Certificate file found: /etc/ssl/certs/veilCert.pem
coturn  | 0: (1): INFO: Private key file found: /etc/ssl/certs/veilKey.pem

I am receiving this strange log in which Coturn says it can not find the private key, but right after, it says it is found.

I followed the previous answer and changed the permission to 0644, but it's not working. Then, tried again with 0600, but it was still not working. Here is the docker compose file:

services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./veilCert.pem:/etc/ssl/certs/veilCert.pem:ro
      - ./veilKey.pem:/etc/ssl/certs/veilKey.pem:ro
    restart: always
    network_mode: host
    pull_policy: always

**Comment by bonzonkim** [comment]
I've faced same issue, and I resolved by give permission with `entrypoint` args


```
version: '3'

services:
  coturn:
    image: coturn/coturn
    container_name: coturn
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
      - ./logs:/var/log/coturn
      - /path/to/cert/cert.crt:/etc/coturn/cert.crt
      - /path/to/cert/cert.key:/etc/coturn/cert.key
    environment:
      - TURN_CERT_PATH=/etc/coturn/cert.crt
      - TURN_KEY_PATH=/etc/coturn/cert.key
    user: root
    entrypoint: /bin/bash -c "chmod 644 /etc/coturn/cert.crt && chmod 644 /etc/coturn/cert.key && /usr/bin/turnserver"
    restart: always

```

**Comment by MrRinkana** [comment]
I have the same identical issue, except I'm not running in docker, but as a systemd service in openSUSE leap 15.6.

turnserver.log:
```
0: (9099): WARNING: cannot find certificate file: /etc/coturn/certs/fullchain.pem (1)
0: (9099): WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: (9099): WARNING: cannot find private key file: /etc/coturn/certs/turn.example.se.key (1)
0: (9099): WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: (9099): INFO: Certificate file found: /etc/coturn/certs/fullchain.pem
0: (9099): INFO: Private key file found: /etc/coturn/certs/turn.example.se.key
```
The files permissions are 644 for the cert, 640 for the key, ownership root:coturn (coturn is set to run as the "coturn" user in systemd). Changing ownership to coturn:coturn does not fix the issue, nor does chmod 644ing the key (which one should not).

Are TLS and DTLS listeners inactive or active in this case?

**Comment by binzhou** [comment]
I managed to resolve this issue - hopefully this will help others too.

Firstly, check if you selinux is enabled and enforcing - if so, your volume bindings need `:z` or `:Z`, otherwise the files won't be readable within the container.

Secondly, if the files are not world-readable, then the default docker setup will fail to read them. This is because the Dockerfiles contain `USER nobody:nogroup` which means only world-readable files can be read within the container. Setting the private key to world readable is a big no-no, so instead you can do the following:

1. run your docker command with `--user root:root` - this will override the `USER` command in the dockerfile and allow coturn to read files that are not world-readable.
2. in your coturn configs, add `proc-user=nobody` and `prod-group=nogroup`. This will force coturn to drop priviledges back to nobody:nogroup just before setting up listeners (but crucially, after configs and files have been read).

Some notes about my particular setup that might differ from yours:

- I'm using podman not docker
- I'm running rootless, so even `--user root:root` doesn't actually give coturn root on the host at any point.

**Comment by zyrakq** [comment]
Alternatively, add a container that will correct file permissions:

```yml title:docker-compose.yml
services:
  coturn:
    container_name: coturn
    image: docker.io/coturn/coturn
    restart: unless-stopped
    network_mode: "host"
    configs:
      - source: turnserver
        target: /etc/coturn/turnserver.conf
    depends_on:
      fix-certs:
        condition: service_completed_successfully
    volumes:
      - letsencrypt-certs:/certs

  fix-certs:
    container_name: fix-certs
    image: busybox
    user: "root"
    environment:
      LETSENCRYPT_HOST: ${COTURN_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - letsencrypt-certs:/certs
    command: sh -c "chmod 644 /certs/${COTURN_DOMAIN}/key.pem 2>/dev/null || true; echo 'Permissions fixed'"

configs:
  turnserver:
    content: |
      use-auth-secret
      static-auth-secret=${COTURN_SECRET_KEY}
      realm=${COTURN_DOMAIN}
      cert=/certs/${COTURN_DOMAIN}/fullchain.pem
      pkey=/certs/${COTURN_DOMAIN}/key.pem

volumes:
  letsencrypt-certs:
    external: true
```
