### ISSUE TITLE
Can I deploy Turn servers on Kubernetes

### ISSUE THREAD

**Issue by raccoonback** [coturn/coturn#504]
Hi 
I'm working on deploying a coturn project to Kubernetes.

I have succeeded in deploying STUN server to Kubernetes, 
but when TURN server is deployed, **there is an issue that it is not distributed to the same pod among peers.** 😥😥😥

![image](https://user-images.githubusercontent.com/16451031/76188192-d75ba280-621a-11ea-851e-10f5a18c1445.png)

As shown in the figure below, a "Send Idication XOR-PEER-ADDRESS" request is sent to different POD IPs.

🙋‍♂️🙋‍♂️🙋‍♂️
## Questions
1. Is it possible to deploy a TURN server in Kubernetes?
2. Have you had a similar issue?

**Comment by raccoonback** [comment]
@kskewes @MrOne-11 @misi

**Comment by misi** [comment]
I am exploring how k8s networking works. I am experiencing k8s with Calico + Multus, but I don't yet have any solution. If any of you have such working solution already please share it..

**Comment by raccoonback** [comment]
@misi
Thank you for your quick response.
I'll share if it's resolved.

**Comment by misi** [comment]
@raccoonback 
With multus + sbr you can create in k8s such pod where you have global IPv4 and IPv6 and you can use k8s to run coturn. 
Or an alternative to nat(1:1) global ip  to a pod ip with calico and floating IP..
This is my final conclusion.. So the answer is yes.

**Comment by mraerino** [comment]
this is how i did it:

- Make sure your cloud provider is able to give you a static IP, which you can dynamically route to any or all nodes of your cluster
  - on Hetzner Cloud, this is called [Floating IP](https://docs.hetzner.com/de/cloud/floating-ips/faq)
  - AWS has elastic IPs
  - in other providers (e.g. Equinix Metal) or in bare metal you might be able to use [MetalLB](https://metallb.universe.tf/) for it
- configure Multus to have a network that is bound to the primary interface of the node
  <details>
  <summary>YAML</summary>
  
  ```yaml
  apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    name: public-net
    namespace: turn
  spec:
    config: |
      {
        "cniVersion": "0.3.1",
        "type": "ipvlan",
        "master": "eth0",
        "mode": "l2",
        "ipam": {
          "type": "static"
        }
      }
  ```
  </details>
- configure a deployment or daemonset with coturn
  <details>
  <summary>YAML</summary>
  
  ```yaml
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: coturn
    namespace: turn
  spec:
    selector:
      matchLabels:
        app: turn
    template:
      metadata:
        labels:
          app: turn
        annotations:
          k8s.v1.cni.cncf.io/networks: |
            [
              {
                "name": "public-net",
                "ips": ["<public IP>/32"]
              }
            ]
      spec:
        initContainers:
          - name: routing-setup
            image: alpine
            command:
              - /bin/sh
              - -c
              - |
                # Service reachability
                GW=$(ip -o route get 10.42.0.0 | awk {'print $3'})
                ip route add 10.43.0.0/16 via $GW dev eth0

                # Default route via public IP
                ip route delete default
                ip route add <router> dev net1
                ip route add default via <router> dev net1
            securityContext:
              privileged: true
              runAsUser: 0
        containers:
          - name: coturn
            image: coturn/coturn:4.5.2
  ```
  </details>
  - be careful: you can never have more than 1 pod of these per node, because that would lead to IP assignment collisions. therefore i used a daemonset because my cluster is small
  - a deployment with a single replica would work, but not be HA
  
- you can use a second container in the pod to help with network debugging
  <details>
  <summary>YAML</summary>

  ```yaml
        - name: debug
          image: nicolaka/netshoot
          command:
            - /bin/sleep
            - infinity
          securityContext:
            privileged: true
            runAsUser: 0
  ```
  </details>
  
  - this will have `tcpdump` and the ability to run any `iproute2` command
  
- to allow getting a cert for `turns` i'm using cert-manager with socat as a TCP proxy
  <details>
  <summary>YAML</summary>

  ```yaml
          - name: acme-proxy
          image: alpine/socat
          command:
            - socat
            - tcp-listen:80,fork,reuseaddr
            - tcp-connect:<ingress>.svc.cluster.local:80
  ```
  </details>
