### ISSUE TITLE
Can you provide a prometheus blackbox probe definition ? 

### ISSUE THREAD

**Issue by rgarrigue** [coturn/coturn#804]
Hi there

I'ld like to monitor my stun service from outside. I was thinking I could use prometheus' blackbox exporter if I knew a bit of the protocol, just enough to valid it's STUN answering. Or TURN why not. Exactly what you'ld type through netcat.

Here's an example for smtp https://github.com/prometheus/blackbox_exporter/blob/master/example.yml#L86-L99

```yaml
  smtp_starttls:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^220 ([^ ]+) ESMTP (.+)$"
        - send: "EHLO prober\r"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS\r"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober\r"
        - expect: "^250-AUTH"
        - send: "QUIT\r"
```

Can you help on this ? Just a copy/paste of your terminal after doing this over netcat would be enough for me.

Thanks & regards
