### ISSUE TITLE
Host your own stun/turn server inside kubernetes and connect it to workadventure

### ISSUE THREAD

**Issue by victorgetz** [coturn/coturn#821]
Hi,

i just wanted to ask if you are interested into a documentation how to host your own coturn setup and connect it to workadventure.

I created this helm chart: https://github.com/iits-consulting/coturn-chart

It works with traefik. I tested it with TCP and UDP and it works like a charm.

Steps to set it up

1. Install helm chart and override this values

```
  coturn:
    realm: "my-turn-domain.de"
    authentification:
      username: coturn
      password: "12345-super-secure"
```
2. Inside your traefik helm chart add this lines
```
  ports:
    coturn-tcp:
      exposedPort: 8443
      port: 8444
      expose: true
      protocol: TCP
```
3. Map your "my-turn-domain.de" to your traefik
4. Inside workadventure set this Environment variables
```
    - name: 'STUN_SERVER'
      value: "stun:my-turn-domain.de:8443?transport=tcp"
    - name: 'TURN_SERVER'
      value: "turn:my-turn-domain.de:8443?transport=tcp"
    - name: 'TURN_USER'
      value: "coturn"
    - name: 'TURN_PASSWORD'
      value: "12345-super-secure"
```
