### ISSUE TITLE
Question: Docker-compose with nodejs

### ISSUE THREAD

**Issue by PodaruDragos** [coturn/coturn#824]
Is there any example that uses docker-compose with nodejs ? 
If someone can provide a basic guidance or example it will be much appreciated.

**Comment by tyranron** [comment]
@PodaruDragos what do you by "example that uses docker-compose with nodejs"? How exactly you're supposed to use Coturn with NodeJS app? Most of the time they're used fully decoupled, so you shouldn't bother whether there is a NodeJS app or something else.

**Comment by PodaruDragos** [comment]
@tyranron sorry for maybe misplacing the question. What I am asking is if there is an example to actually run `coturn` in a docker-compose file and how to proper configure it to actually work. I omitted the node part from `docker-compose` since my question was not properly asked.


```
version: '3.8'

services: 
  coturn:
    container_name: coturn
    image: coturn/coturn:latest
    network_mode: host
    ports:
      - '5349:5349'
      - '5349:5349/udp'
      - '5350:5350'
      - '5350:5350/udp'
      - '443:443'
      - '443:443/udp'
    restart: always
  
  database:
    container_name: database
    env_file: .env
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: {}
```

```
coturn    | 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
coturn    | 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
coturn    | 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
coturn    | 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
coturn    | 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
coturn    | 0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
```
How can I configure `turnserver.conf` ?
Is there any way I can specify the things needed from an `.env` file? and if so can you point into a direction since I din't find anything in the docs.

If the question is not good enough or if the docs mentions something like this, fell free to close this question. Thanks.

**Comment by PodaruDragos** [comment]
Thanks for the answser. the stun server seems to work now.

Using this config
```
listening-port=3478
tls-listening-port=5349

min-port=49152
max-port=65535

cert=/etc/ssl/certs/cert.pem
pkey=/etc/ssl/private/privkey.pem

user=test:test

fingerprint
lt-cred-mech
no-cli
syslog
verbose
```

and this docker-compose 
```
services:
  coturn:
    container_name: coturn
    image: coturn/coturn:latest
    ports:
## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      - "80:80"
      - "80:80/udp"
## STUN/TURN SSL
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
      - "443:443"
      - "443:443/udp"
    restart: always
    volumes:
      - ./config/coturn/turnserver.conf:/etc/turnserver.conf:ro
      - ./config/ssl/key.pem:/etc/ssl/private/privkey.pem:ro
      - ./config/ssl/cert.pem:/etc/ssl/certs/cert.pem:ro
      
      ......
```
I can't seem to get it to work on `trickleICE`. I always get this error

```
The server stun:127.0.0.1:3478 returned an error with code=701:
STUN server address is incompatible.
The server turn:127.0.0.1:3478?transport=udp returned an error with code=401:
Unauthorized
```

Any help is much appreciated
