### ISSUE TITLE
docker logs and timezone

### ISSUE THREAD

**Issue by rajil** [coturn/coturn#940]
I have specified the timezone in docker-compose yaml file, but still `docker logs coturn -t` shows the UTC time. Is there any way to specify a timezone in the docker image?

Here is my compose file,
```
version: '3.7'
services:
    coturn:
        container_name: coturn
        network_mode: host
        volumes:
            - '/home/ubuntu/my.conf:/etc/coturn/turnserver.conf'
        image: coturn/coturn
        restart: always
        environment:
          TZ: "Europe/London"
```
