### ISSUE TITLE
Issues with docker setup with network

### ISSUE THREAD

**Issue by d3hof** [coturn/coturn#966]
So we have kind of a "special" set up, we are running one Bigbluebutton-node with a dockerized coturn, but for some reason if i turn on relay mode only in firefox I can't get an connection to audio/video/screenshare.

We are using the following docker-compose.yml

```
version: "3"
services:
  coturn:
    image: coturn/coturn:4.5.2-r14
    restart: always
    command: ["turnserver", "--log-file=stdout"]
    volumes:
      - ../coturn/turnserver.conf:/etc/turnserver.conf:ro
      - ./certs/privkey.pem:/etc/ssl/turnprivkey.pem:ro
      - ./certs/fullchain.pem:/etc/ssl/certs/turncert.pem:ro
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: syslog
      options:
        tag: docker-coturn
        cache-disabled: "true"
```

I know that the docker-compose file in the repo opens every port for itself, but that doesn't work, because we have to bind to a specific external ip on the host. And If i have to do it with services.coturn.ports it starts a docker-proxy process for every openend port and that's about 20k ish what kills the server (https://github.com/moby/moby/issues/11185).

```

listening-port=3478

tls-listening-port=443

alt-tls-listening-port=5349

listening-ip=ipv4
listening-ip=ipv6


min-port=49152
max-port=65535

verbose

fingerprint


use-auth-secret

static-auth-secret=xxxxx

realm=<xxxx>

pkey=/etc/ssl/turnprivkey.pem
cert=/etc/ssl/certs/turncert.pem

no-tlsv1
no-tlsv1_1

keep-address-family

no-rfc5780

no-stun-backward-compatibility

response-origin-only-with-rfc5780

denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.88.99.0-192.88.99.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=240.0.0.0-255.255.255.255
denied-peer-ip=::1
denied-peer-ip=64:ff9b::-64:ff9b::ffff:ffff
denied-peer-ip=::ffff:0.0.0.0-::ffff:255.255.255.255
denied-peer-ip=100::-100::ffff:ffff:ffff:ffff
denied-peer-ip=2001::-2001:1ff:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=2002::-2002:ffff:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff


lt-cred-mech

cipher-list="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
```
The logs always report the following:

`Sep  1 15:17:28 xxx docker-coturn[1936]: 2734: : session 002000000000000063: closed (2nd stage), user <xxxxxxxxxx> realm <xxxxxxx> origin <>, xxxx:3478, remote xxxx:59664, reason: allocation watchdog determined stale session state`

The above is our current turnserver.conf. Has anyone idea what could be done to improve the setup or/and solve the issue?

Is this setup even recommended/possible?

Kind Regards and thanks for the help already.
